# Generated by Django 4.1.1 on 2022-09-24 09:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='information',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='preview_info',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
